language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aashiq2691/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aashiq2691/react-test npm test

after_success:
  - docker build -t aashiq2691/multi-client ./client
  - docker build -t aashiq2691/multi-nginx ./nginx
  - docker build -t aashiq2691/multi-server ./server
  - docker build -t aashiq2691/multi-worker ./worker
  # Login to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  #Push Images to docker hub
  - docker push aashiq2691/multi-client
  - docker push aashiq2691/multi-nginx
  - docker push aashiq2691/multi-server
  - docker push aashiq2691/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-797274960741"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY